### ISSUE TITLE
if/else fails to resolve else condition with preceding HTML comment

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/teddy#198]
Here's an example:

```
<if doesntExist>
  <p>Nope</p>
</if>

<!-- Cool HTML comment chilling here -->
<else>
  <p>Stuff I'd like to see</p>
</else>
```

Will resolve as just: 

`<!-- Cool HTML comment chilling here -->`

Generally one wouldn't expect there to be anything between an if statement and it's else condition, but a comment is an exception to that.

**Comment by kethinov** [comment]
Another exception would be excessive amounts of whitespace. Does the PR handle that?
