### ISSUE TITLE
Include template but not render template

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/teddy#201]
Right now it is impossible (from what I can see) to include a template, but not have the contents of that template rendered.

For example say you have a template called `test.html` which looks like:

**test.html**
```html
<p>{varThatWeWantToRenderOnTheClient}</p>
```

And a main template which is being render on request which looks like:

**index.html**
```html
<h1>Hello World</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<p>{varThatWeWantToRenderOnTheClient}</p>
<template>
  <include src='test.html'>
</template>
```

**model.js**
With a model:

```js
{ varThatWeWantToRenderOnTheClient: 'Hello World 2' }
```

This will render:

```html
<h1>Hello World</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<p>Hello World 2</p>
<template>
  <p>Hello World 2</p>
</template>
```

What I want is the template to be sent un-rendered to the browser, which would look like:

```html
<h1>Hello World</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
<p>Hello World 2</p>
<template>
    <p>{varThatWeWantToRenderOnTheClient}</p>
</template>
```

so that way I could grab the contents from the template tag and do client side Teddy templating.

**Comment by kethinov** [comment]
Proposed syntax to solve this:

```html
<include src='test.html' noparse></include>

{! also supported !}
<include src='test.html' noteddy></include>
```

Once implemented, will need to be added to: https://github.com/rooseveltframework/teddy#non-parsed-blocks
