### ISSUE TITLE
Is there styling options to create components ?

### ISSUE THREAD

**Issue by pushqrdx** [rooseveltframework/teddy#213]
I really like the syntax of this lang, but is there anyway i can leverage it as a full ui framework (data bindings and component specific styling ?

**Comment by kethinov** [comment]
If you combine it with other small libraries that do those things, yeah, e.g. [bind.js](https://gomakethings.com/two-way-data-binding-with-vanilla-javascript) for data binding. For component-specific styling, there are a lot of approaches. The future is probably native web components. If you want to use those, look into polyfills. The more lightweight approach that works today is just plain old CSS namespacing, e.g. reserving a className for whatever component you're building and writing all CSS within that class, which is unsophisticated but works fine and is more or less what the big frameworks are doing under the hood anyway.

**Comment by kethinov** [comment]
Closing this. Feel free to reopen if you have more questions.
