### ISSUE TITLE
Error Checking for <loop>

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/teddy#288]
I had an instance where I passed in an object into a <loop> which I thought was an array and ended up being a singular object and it ended up in resulting in a TypeError that didn't directly relate to the issue that the model was expecting an array and didn't get one.

I think that it would be good to try writing some error checking on parsing the loop tag so if a user passes in an incorrect model that they weren't trying to push in (ex: an object when expecting to pass an array), Teddy could output some type of warning or error to the console.

**Comment by kethinov** [comment]
No idea what this is about. Reopen with a specific test case if you can produce one.
