### ISSUE TITLE
Look to move functionality of teddy.compile towards similar to other template engines

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/teddy#299]
For a large amount of template engines, the `compile` method takes in a template and outputs a function which when given data, will render out HTML.

Here are some various other templating engines which do this:

* **Pug**: https://pugjs.org/api/reference.html#pugcompilesource-options
* **Handlebars**: http://handlebarsjs.com/ (scroll down to where it says "Compile a template in JavaScript by using Handlebars.compile")
* **EJS**: http://ejs.co/#docs

**Comment by kethinov** [comment]
`teddy.compile` was removed in 0.6.0 but this issue is still valid because a new `teddy.compile` could be added later which introduced this functionality.
