### ISSUE TITLE
Needs testing for Arrays containing arrays (Looping)

### ISSUE THREAD

**Issue by dishad** [rooseveltframework/teddy#404]
Most of the nested arrays looping tests are against the `nestedObjects` array of objects. If we try to run teddy looping on an array of arrays I get errors.

**Comment by kethinov** [comment]
I [wrote a test to prove this is an issue](https://github.com/rooseveltframework/teddy/blob/b71e33cfa4563989bb5c7502a339263b62bcb583/test/looping.js#L39-L43), but I couldn't figure out how to fix it. @dishad can you take a look?
