### ISSUE TITLE
HTML comments inside of conditionals breaks

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/teddy#489]
Example

```
<unless selected>
  <!-- A comment -->
  <h2>Selected</h2>
</unless>
<else>
  <h2>Not selected</h2>
</else>
```

Error

```
TypeError: Cannot read property '0' of undefined
```

Skipped unit test can be found [here](https://github.com/rooseveltframework/teddy/blob/2cca0b731c2c0d6382eea06e85fc59353682559d/test/conditionals.js#L372-L375) added in #488

**Comment by kethinov** [comment]
Fixed in 0.6.0.
